version: '3.9'

services: 
    analysis_app:
        container_name: hunter_service
        image: 161.189.68.1/library/analysis_hunter:latest
        restart: always
        build: ./deploy/flask_app
        volumes: 
            - ./analysis:/var/analysis/
            - ./log/analysis:/var/log/analysis
            - ./log/ti_audit:/var/log/ti_audit
            - ./conf:/etc/analysis/
        env_file:
            - envs/certificate.env
            - envs/directory.env
            - envs/network.env
        ports:
            - "8000:8000"
      
    nginx:
        container_name: nginx_service
        image: 161.189.68.1/library/analysis_nginx:latest
        restart: always
        build: ./deploy/nginx
        volumes: 
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
        depends_on:
            - analysis_app